apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: acme
spec:
  acme:
    email: me@clayenkitten.dev
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme
    solvers:
    - http01:
        ingress:
          class: traefik
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: capydemia-cert
spec:
  secretName: capydemia-cert
  dnsNames:
    - "{{ .Values.domain }}"
  issuerRef:
    name: acme
    kind: Issuer
