apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: capydemia-ingress
  labels:
    app.kubernetes.io/part-of: capydemia
spec:
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: capydemia-web
            port:
              number: 3000
