apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: capydemia-ingress
spec:
  routes:
    - kind: Rule
      match: Host(`{{ .Values.domain }}`)
      services:
      - name: capydemia-web
        port: 3000
  tls:
    secretName: capydemia-cert
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: capydemia-ingress-http
spec:
  entryPoints: [web]
  routes:
    - kind: Rule
      match: Host(`{{ .Values.domain }}`)
      middlewares:
        - name: redirect-https
      services:
        - name: capydemia-web
          port: 3000
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
spec:
  redirectScheme:
    scheme: https
    permanent: true
