services:
  dev:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    expose: [3000]
    env_file: [../.env]
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/app:cached

  db:
    extends:
      service: db
      file: ../compose.yaml

volumes:
  db:
