name: Check

on:
  workflow_dispatch:
  workflow_call:

jobs:
  check-and-test:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js 21.x
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
          cache: "npm"
      - run: npm check:format
        if: ${{ github.event_name == 'pull_request' }}
      - run: npm ci
      - name: Check
        run: npm run check
      - name: Test
        run: npm run test
