name: Check and Test

on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - edited

jobs:
  check-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js 21.x
      uses: actions/setup-node@v4
      with:
        node-version: 21.x
        cache: 'npm'
    - run: npm ci
    - name: Check
      run: npm run check
    - name: Test
      run: npm run test
