name: Check

on:
  workflow_dispatch:
  workflow_call:

jobs:
  check-and-test:
    name: Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js 21.x
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
          cache: "npm"
          cache-dependency-path: web/package-lock.json
      - run: npm ci
      - name: Check formatting
        run: npm run check:format
        if: ${{ github.event_name == 'pull_request' }}
      - name: Check
        id: check
        run: npm run check
        if: ${{ !cancelled() }}
      - name: Test
        run: npm run test
        if: ${{ !cancelled() && steps.check.conclusion == 'success' }}
