name: Deploy
permissions: write-all

on:
  workflow_dispatch:
  registry_package:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DOMAIN }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: cd ~/capydemia && git reset --hard @{u} && git pull && docker compose pull && docker compose up -d
