name: Build and Deploy
permissions: write-all

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build image
    uses: ClayenApps/actions/.github/workflows/docker-ghcr.yml@main

  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DOMAIN }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: cd ~/capydemia && git reset --hard @{u} && git pull && docker compose pull && docker compose up -d
