name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            rm -rf /tmp/capydemia-helm
            helm pull oci://ghcr.io/clayenkitten/capydemia-helm \
              --untar \
              --destination /tmp
            helm upgrade --install capydemia \
              /tmp/capydemia/capydemia-helm/ \
              --values /tmp/capydemia-helm/${{ vars.VALUES_FILE }} \
              --namespace ${{ vars.NAMESPACE }} \
              --create-namespace
